OdeToFood/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OdeToFood/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

OdeToFood/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

OdeToFood/Pages/Restaurants/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data.Abstract;

namespace OdeToFood.Pages.Restaurants
{
    public class DeleteModel : PageModel
    {
        private readonly IRestaurantData _restaurantData;

        public DeleteModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }

        public Restaurant Restaurant { get; set; }

        public IActionResult OnGet(Guid restaurantId)
        {
            Restaurant = _restaurantData.GetById(restaurantId);
            if (Restaurant == null) return RedirectToPage("./NotFound");
            return Page();
        }

        public async Task<IActionResult> OnPost(Guid restaurantId)
        {
            Restaurant restaurant = _restaurantData.Delete(restaurantId);
            await _restaurantData.Commit();

            if (restaurant == null) return RedirectToPage("./NotFound");

            TempData["Message"] = $"{restaurant.Name} deleted.";
            return RedirectToPage("./List");
        }
    }
}

OdeToFood/Pages/Restaurants/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;
using OdeToFood.Data.Abstract;

namespace OdeToFood.Pages.Restaurants
{
    public class DetailModel : PageModel
    {
        private readonly IRestaurantData _restaurantData;

        public Restaurant Restaurant { get; set; }
        
        [TempData]
        public string Message { get; set; }

        public DetailModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }

        public IActionResult OnGet(Guid restaurantId)
        {
            Restaurant = _restaurantData.GetById(restaurantId);
            if (Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
    }
}

OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdeToFood.Core;
using OdeToFood.Data;
using OdeToFood.Data.Abstract;

namespace OdeToFood.Pages.Restaurants
{
    public class EditModel : PageModel
    {
        private readonly IRestaurantData _restaurantData;
        private readonly IHtmlHelper _htmlHelper;

        public EditModel(IRestaurantData restaurantData, IHtmlHelper htmlHelper)
        {
            _restaurantData = restaurantData;
            _htmlHelper = htmlHelper;
            CuisineTypes = _htmlHelper.GetEnumSelectList<CuisineType>().OrderBy(c => c.Text);
        }

        [BindProperty]
        public Restaurant Restaurant { get; set; }
        public IEnumerable<SelectListItem> CuisineTypes { get; set; }

        public IActionResult OnGet(Guid? restaurantId)
        {
            if (restaurantId.HasValue)
            {
                Restaurant = _restaurantData.GetById(restaurantId.Value);
            }
            else
            {
                Restaurant = new Restaurant();
            }

            if (Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (Restaurant.Id != Guid.Empty)
            {
                TempData["Message"] = "Restaurant updated.";
                Restaurant = _restaurantData.Update(Restaurant);
            }
            else 
            {
                TempData["Message"] = "Restaurant created.";
                await _restaurantData.Add(Restaurant);
            }
            await _restaurantData.Commit();
            return RedirectToPage("./Detail", new { restaurantId = Restaurant.Id  });
        }
    }
}

OdeToFood/Pages/Restaurants/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using OdeToFood.Core;
using OdeToFood.Data;
using OdeToFood.Data.Abstract;

namespace OdeToFood.Pages.Restaurants
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration _config;
        private readonly IRestaurantData _restaurantData;
        private readonly IFilters _filters;

        public IEnumerable<Restaurant> Restaurants { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; } = string.Empty;

        [BindProperty(SupportsGet = true)]
        public CuisineType SearchCuisine { get; set; } = CuisineType.All;

        [BindProperty(SupportsGet = true)]
        public IEnumerable<Location> Locations { get; private set; }

        [BindProperty(SupportsGet = true)]
        public string SearchLocation { get; set; }

        public ListModel(IConfiguration config, IRestaurantData restaurantData, IFilters filters)
        {
            _config = config;
            _restaurantData = restaurantData;
            _filters = filters;
            Locations = _restaurantData.GetLocationsForDropdown();
        }
        public void OnGet()
        {
            Restaurants = _restaurantData.Get(_filters.ByName(SearchTerm), _filters.ByCuisine(SearchCuisine), _filters.ByLocation(SearchLocation));
        }
    }
}

OdeToFood/ViewComponents/RestaurantCountViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data.Abstract;

namespace OdeToFood.ViewComponents
{
    public class RestaurantCountViewComponent : ViewComponent
    {
        private readonly IRestaurantData _restaurantData;

        public RestaurantCountViewComponent(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }

        public IViewComponentResult Invoke()
        {
            var count = _restaurantData.GetRestaurantsCount();
            return View(count);
        }
    }
}

OdeToFood/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

OdeToFood/Pages/Restaurants/Delete.cshtml
@page "{restaurantId:Guid}"
@model OdeToFood.Pages.Restaurants.DeleteModel
@{
    
}

<h2>Delete</h2>
<div class="alert alert-danger">
    Are you sure you want to delete @Model.Restaurant.Name?
</div>
<form method="post">
    <button type="submit" class="btn btn-danger">Yes</button>
    <a asp-page="List" class="btn btn-primary">No</a>
</form>

OdeToFood/Pages/Restaurants/Detail.cshtml
@page "{restaurantId:Guid}"
@model OdeToFood.Pages.Restaurants.DetailModel
@{
    ViewData["Title"] = "Detail";
}

<h2>@Model.Restaurant.Name</h2>
@if (@Model.Message != null)
{
    <div class="alert alert-info">@Model.Message</div>
}
<h3>@Model.Message</h3>
<div>
    Id: @Model.Restaurant.Id
</div>
<div>
    Location: @Model.Restaurant.Location
</div>
<div>
    Cuisine: @Model.Restaurant.Cuisine
</div>

<a asp-page="./List" class="btn btn-info">All Restaurants</a>

OdeToFood/Pages/Restaurants/Edit.cshtml
@page "{restaurantId:Guid?}"
@using OdeToFood.Core 
@model OdeToFood.Pages.Restaurants.EditModel
@{
}

<h2>Edit Restaurant - @Model.Restaurant.Name</h2>

<form method="post">
    <input type="hidden" asp-for="Restaurant.Id" />
    <div class="form-group">
        <label asp-for="Restaurant.Name"></label>
        <input class="form-control" asp-for="Restaurant.Name" />
        <span class="text-danger" asp-validation-for="Restaurant.Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Location.City"></label>
        <input class="form-control" asp-for="Restaurant.Location.City" />
        <span class="text-danger" asp-validation-for="Restaurant.Location.City"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Location.Country"></label>
        <input class="form-control" asp-for="Restaurant.Location.Country" />
        <span class="text-danger" asp-validation-for="Restaurant.Location.Country"></span>
    </div>
    <div class="form-group">
        <label asp-for="Restaurant.Cuisine"></label>
        <select class="form-control" asp-for="Restaurant.Cuisine" asp-items="Model.CuisineTypes"></select>
    </div>
    <button type="submit" class="btn btn-info">Save</button>
</form>

OdeToFood/Pages/Restaurants/List.cshtml
@page
@using OdeToFood.Core
@model OdeToFood.Pages.Restaurants.ListModel
@{
}

<h1>Restaurants</h1>

<form method="get">
    <div class="row">
        <div class="col-sm-4">
            <div class="input-group">
                <input type="search" class="form-control" asp-for="SearchTerm" placeholder="Restaurant name">
            </div>
        </div>
        <div class="col-sm-3">
            <div class="input-group">
                <select class="form-control" asp-for="SearchCuisine" asp-items="Html.GetEnumSelectList<CuisineType>()"></select>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="input-group">
                @Html.DropDownListFor(l => l.SearchLocation, new SelectList(Model.Locations, "City", "City"), "All Locations", new { @class = "form-control" })
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                <button class="btn btn-outline-primary" type="submit" title="Search Restaurant"><i class="fas fa-search"></i></button>
                <a class="btn btn-outline-primary" asp-page="./Edit" type="button" title="Create New Restaurant"><i class="fas fa-plus"></i></a>
            </div>
        </div>
    </div>
</form>

@foreach (var restaurant in Model.Restaurants)
{
    <partial name="_Summary" model="restaurant" />
}

OdeToFood/Pages/Restaurants/NotFound.cshtml
@page

@{
    ViewData["Title"] = "Not Found";
}

<h2>Your restaurant was not found</h2>
<a asp-page="./List" class="btn btn-info">All restaurants</a>

OdeToFood/Pages/Restaurants/_Summary.cshtml
@using OdeToFood.Core
@model Restaurant

<div class="card mb-3">
    <div class="card card-header alert-primary">
        <div class="row">
            <div class="col">
                <h3>@Model.Name</h3>
            </div>
            <div class="col float-right">
                <span class="float-right">
                    <a class="btn btn-info" asp-page="./Detail" asp-route-restaurantId="@Model.Id" title="Details"><i class="fas fa-search-plus"></i></a>
                    <a class="btn btn-info" asp-page="./Edit" asp-route-restaurantId="@Model.Id" title="Edit"><i class="fas fa-edit"></i></a>
                    <a class="btn btn-info" asp-page="./Delete" asp-route-restaurantId="@Model.Id" title="Delete"><i class="fas fa-trash"></i></a>
                </span>
            </div>
        </div>
    </div>
    <div class="card card-body">
        <span>Location: @Model.Location.City, @Model.Location.Country</span>
        <span>Cuisine: @Model.Cuisine</span>
    </div>
</div>

OdeToFood/Pages/Shared/Components/RestaurantCount/Default.cshtml
@model int

<span>Listing @Model restaurants in Croatia, <a asp-page="/Restaurants/List">see them all</a>!</span>
    

OdeToFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OdeToFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OdeToFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Restaurants/List">Restaurants</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - OdeToFood - <vc:restaurant-count></vc:restaurant-count>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>